version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_caja_ahorro
    restart: always
    environment:
      MYSQL_DATABASE: sistema_caja
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - ./datos_mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_caja_ahorro
    links:
      - db:db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password123